# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_expected_marginal_cost.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog_expected_marginal_cost(object):
    def setupUi(self, dialog_expected_marginal_cost):
        dialog_expected_marginal_cost.setObjectName("dialog_expected_marginal_cost")
        dialog_expected_marginal_cost.resize(469, 421)
        font = QtGui.QFont()
        font.setPointSize(18)
        dialog_expected_marginal_cost.setFont(font)
        dialog_expected_marginal_cost.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_expected_marginal_cost)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStatusTip("")
        self.label.setWhatsThis("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.dialog_marginal_cost_plant_comboBox = QtWidgets.QComboBox(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_marginal_cost_plant_comboBox.sizePolicy().hasHeightForWidth())
        self.dialog_marginal_cost_plant_comboBox.setSizePolicy(sizePolicy)
        self.dialog_marginal_cost_plant_comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.dialog_marginal_cost_plant_comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dialog_marginal_cost_plant_comboBox.setFont(font)
        self.dialog_marginal_cost_plant_comboBox.setObjectName("dialog_marginal_cost_plant_comboBox")
        self.gridLayout.addWidget(self.dialog_marginal_cost_plant_comboBox, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dialog_marginal_cost_label_calculated_marginal_cost = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_marginal_cost_label_calculated_marginal_cost.sizePolicy().hasHeightForWidth())
        self.dialog_marginal_cost_label_calculated_marginal_cost.setSizePolicy(sizePolicy)
        self.dialog_marginal_cost_label_calculated_marginal_cost.setMinimumSize(QtCore.QSize(0, 0))
        self.dialog_marginal_cost_label_calculated_marginal_cost.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dialog_marginal_cost_label_calculated_marginal_cost.setFont(font)
        self.dialog_marginal_cost_label_calculated_marginal_cost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dialog_marginal_cost_label_calculated_marginal_cost.setObjectName("dialog_marginal_cost_label_calculated_marginal_cost")
        self.horizontalLayout_4.addWidget(self.dialog_marginal_cost_label_calculated_marginal_cost)
        self.label_3 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 8, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setWhatsThis("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.dialog_marginal_cost_source = QtWidgets.QLabel(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dialog_marginal_cost_source.setFont(font)
        self.dialog_marginal_cost_source.setObjectName("dialog_marginal_cost_source")
        self.gridLayout.addWidget(self.dialog_marginal_cost_source, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dialog_marginal_cost_total_production_lineEdit = QtWidgets.QLineEdit(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_marginal_cost_total_production_lineEdit.sizePolicy().hasHeightForWidth())
        self.dialog_marginal_cost_total_production_lineEdit.setSizePolicy(sizePolicy)
        self.dialog_marginal_cost_total_production_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dialog_marginal_cost_total_production_lineEdit.setFont(font)
        self.dialog_marginal_cost_total_production_lineEdit.setText("")
        self.dialog_marginal_cost_total_production_lineEdit.setFrame(True)
        self.dialog_marginal_cost_total_production_lineEdit.setClearButtonEnabled(True)
        self.dialog_marginal_cost_total_production_lineEdit.setObjectName("dialog_marginal_cost_total_production_lineEdit")
        self.horizontalLayout_3.addWidget(self.dialog_marginal_cost_total_production_lineEdit)
        self.label_4 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.dialog_marginal_cost_fuel_cost = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_marginal_cost_fuel_cost.sizePolicy().hasHeightForWidth())
        self.dialog_marginal_cost_fuel_cost.setSizePolicy(sizePolicy)
        self.dialog_marginal_cost_fuel_cost.setObjectName("dialog_marginal_cost_fuel_cost")
        self.horizontalLayout_7.addWidget(self.dialog_marginal_cost_fuel_cost)
        self.label_16 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.gridLayout.addLayout(self.horizontalLayout_7, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dialog_marginal_cost_capacity = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_marginal_cost_capacity.sizePolicy().hasHeightForWidth())
        self.dialog_marginal_cost_capacity.setSizePolicy(sizePolicy)
        self.dialog_marginal_cost_capacity.setObjectName("dialog_marginal_cost_capacity")
        self.horizontalLayout_5.addWidget(self.dialog_marginal_cost_capacity)
        self.label_9 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.dialog_marginal_cost_variable_cost = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_marginal_cost_variable_cost.sizePolicy().hasHeightForWidth())
        self.dialog_marginal_cost_variable_cost.setSizePolicy(sizePolicy)
        self.dialog_marginal_cost_variable_cost.setObjectName("dialog_marginal_cost_variable_cost")
        self.horizontalLayout_6.addWidget(self.dialog_marginal_cost_variable_cost)
        self.label_11 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dialog_marginal_cost_own_production_lineEdit = QtWidgets.QLineEdit(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_marginal_cost_own_production_lineEdit.sizePolicy().hasHeightForWidth())
        self.dialog_marginal_cost_own_production_lineEdit.setSizePolicy(sizePolicy)
        self.dialog_marginal_cost_own_production_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dialog_marginal_cost_own_production_lineEdit.setFont(font)
        self.dialog_marginal_cost_own_production_lineEdit.setText("")
        self.dialog_marginal_cost_own_production_lineEdit.setFrame(True)
        self.dialog_marginal_cost_own_production_lineEdit.setClearButtonEnabled(True)
        self.dialog_marginal_cost_own_production_lineEdit.setObjectName("dialog_marginal_cost_own_production_lineEdit")
        self.horizontalLayout_2.addWidget(self.dialog_marginal_cost_own_production_lineEdit)
        self.label_15 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dialog_marginal_cost_label_production = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_marginal_cost_label_production.sizePolicy().hasHeightForWidth())
        self.dialog_marginal_cost_label_production.setSizePolicy(sizePolicy)
        self.dialog_marginal_cost_label_production.setMinimumSize(QtCore.QSize(0, 0))
        self.dialog_marginal_cost_label_production.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dialog_marginal_cost_label_production.setFont(font)
        self.dialog_marginal_cost_label_production.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dialog_marginal_cost_label_production.setObjectName("dialog_marginal_cost_label_production")
        self.horizontalLayout_8.addWidget(self.dialog_marginal_cost_label_production)
        self.label_5 = QtWidgets.QLabel(dialog_expected_marginal_cost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.dialog_expected_marginal_cost_button_calculate = QtWidgets.QPushButton(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dialog_expected_marginal_cost_button_calculate.setFont(font)
        self.dialog_expected_marginal_cost_button_calculate.setObjectName("dialog_expected_marginal_cost_button_calculate")
        self.horizontalLayout.addWidget(self.dialog_expected_marginal_cost_button_calculate)
        self.dialog_expected_marginal_cost_button_close = QtWidgets.QPushButton(dialog_expected_marginal_cost)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dialog_expected_marginal_cost_button_close.setFont(font)
        self.dialog_expected_marginal_cost_button_close.setObjectName("dialog_expected_marginal_cost_button_close")
        self.horizontalLayout.addWidget(self.dialog_expected_marginal_cost_button_close)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dialog_expected_marginal_cost)
        QtCore.QMetaObject.connectSlotsByName(dialog_expected_marginal_cost)

    def retranslateUi(self, dialog_expected_marginal_cost):
        _translate = QtCore.QCoreApplication.translate
        dialog_expected_marginal_cost.setWindowTitle(_translate("dialog_expected_marginal_cost", "Expected marginal cost calculator"))
        self.label_13.setText(_translate("dialog_expected_marginal_cost", "Production:"))
        self.label.setText(_translate("dialog_expected_marginal_cost", "Own capacity used:"))
        self.dialog_marginal_cost_label_calculated_marginal_cost.setWhatsThis(_translate("dialog_expected_marginal_cost", "Your estimated marginal cost"))
        self.dialog_marginal_cost_label_calculated_marginal_cost.setText(_translate("dialog_expected_marginal_cost", "-"))
        self.label_3.setText(_translate("dialog_expected_marginal_cost", "NOK/MWh"))
        self.label_2.setText(_translate("dialog_expected_marginal_cost", "Others capacity:"))
        self.label_8.setText(_translate("dialog_expected_marginal_cost", "Fuel cost:"))
        self.label_7.setText(_translate("dialog_expected_marginal_cost", "Variable cost:"))
        self.label_6.setText(_translate("dialog_expected_marginal_cost", "Actual capacity:"))
        self.dialog_marginal_cost_source.setText(_translate("dialog_expected_marginal_cost", "Source"))
        self.dialog_marginal_cost_total_production_lineEdit.setWhatsThis(_translate("dialog_expected_marginal_cost", "Set a guess for  the capacity use of the other players in the market "))
        self.label_4.setText(_translate("dialog_expected_marginal_cost", "MW"))
        self.dialog_marginal_cost_fuel_cost.setText(_translate("dialog_expected_marginal_cost", "-"))
        self.label_16.setText(_translate("dialog_expected_marginal_cost", "NOK/GWh"))
        self.label_12.setText(_translate("dialog_expected_marginal_cost", "Marginal cost:"))
        self.dialog_marginal_cost_capacity.setText(_translate("dialog_expected_marginal_cost", "-"))
        self.label_9.setText(_translate("dialog_expected_marginal_cost", "MW"))
        self.dialog_marginal_cost_variable_cost.setText(_translate("dialog_expected_marginal_cost", "-"))
        self.label_11.setText(_translate("dialog_expected_marginal_cost", "NOK/MWh"))
        self.dialog_marginal_cost_own_production_lineEdit.setWhatsThis(_translate("dialog_expected_marginal_cost", "Set how much of your own capacity should be used"))
        self.label_15.setText(_translate("dialog_expected_marginal_cost", "MW"))
        self.dialog_marginal_cost_label_production.setWhatsThis(_translate("dialog_expected_marginal_cost", "Your prouction at the inputted capacity use"))
        self.dialog_marginal_cost_label_production.setText(_translate("dialog_expected_marginal_cost", "-"))
        self.label_5.setText(_translate("dialog_expected_marginal_cost", "GWh"))
        self.dialog_expected_marginal_cost_button_calculate.setText(_translate("dialog_expected_marginal_cost", "Calculate"))
        self.dialog_expected_marginal_cost_button_close.setText(_translate("dialog_expected_marginal_cost", "Close"))

