# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/dialog_settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog_settings(object):
    def setupUi(self, dialog_settings):
        dialog_settings.setObjectName("dialog_settings")
        dialog_settings.resize(328, 341)
        dialog_settings.setMaximumSize(QtCore.QSize(440, 341))
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(dialog_settings)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(dialog_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dialog_settings_horizontalSlider_theme = QtWidgets.QSlider(dialog_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_settings_horizontalSlider_theme.sizePolicy().hasHeightForWidth())
        self.dialog_settings_horizontalSlider_theme.setSizePolicy(sizePolicy)
        self.dialog_settings_horizontalSlider_theme.setMaximum(1)
        self.dialog_settings_horizontalSlider_theme.setOrientation(QtCore.Qt.Horizontal)
        self.dialog_settings_horizontalSlider_theme.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.dialog_settings_horizontalSlider_theme.setObjectName("dialog_settings_horizontalSlider_theme")
        self.verticalLayout_4.addWidget(self.dialog_settings_horizontalSlider_theme)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(dialog_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6 = QtWidgets.QLabel(dialog_settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(dialog_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dialog_settings_horizontalSlider_text_size = QtWidgets.QSlider(dialog_settings)
        self.dialog_settings_horizontalSlider_text_size.setMaximum(2)
        self.dialog_settings_horizontalSlider_text_size.setOrientation(QtCore.Qt.Horizontal)
        self.dialog_settings_horizontalSlider_text_size.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.dialog_settings_horizontalSlider_text_size.setObjectName("dialog_settings_horizontalSlider_text_size")
        self.verticalLayout_5.addWidget(self.dialog_settings_horizontalSlider_text_size)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(dialog_settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2 = QtWidgets.QLabel(dialog_settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_4 = QtWidgets.QLabel(dialog_settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.dialog_settings_button_apply = QtWidgets.QPushButton(dialog_settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dialog_settings_button_apply.setFont(font)
        self.dialog_settings_button_apply.setObjectName("dialog_settings_button_apply")
        self.horizontalLayout_5.addWidget(self.dialog_settings_button_apply)
        self.dialog_settings_button_close = QtWidgets.QPushButton(dialog_settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dialog_settings_button_close.setFont(font)
        self.dialog_settings_button_close.setObjectName("dialog_settings_button_close")
        self.horizontalLayout_5.addWidget(self.dialog_settings_button_close)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(dialog_settings)
        QtCore.QMetaObject.connectSlotsByName(dialog_settings)

    def retranslateUi(self, dialog_settings):
        _translate = QtCore.QCoreApplication.translate
        dialog_settings.setWindowTitle(_translate("dialog_settings", "Settings"))
        self.label.setText(_translate("dialog_settings", "Settings"))
        self.label_7.setText(_translate("dialog_settings", "Theme"))
        self.label_5.setText(_translate("dialog_settings", "Dark"))
        self.label_6.setText(_translate("dialog_settings", "Light"))
        self.label_8.setText(_translate("dialog_settings", "Text size"))
        self.label_3.setText(_translate("dialog_settings", "Small"))
        self.label_2.setText(_translate("dialog_settings", "Medium"))
        self.label_4.setText(_translate("dialog_settings", "Big"))
        self.dialog_settings_button_apply.setText(_translate("dialog_settings", "Apply"))
        self.dialog_settings_button_close.setText(_translate("dialog_settings", "Close"))

