# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_newPlant.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog_newPlant(object):
    def setupUi(self, dialog_newPlant):
        dialog_newPlant.setObjectName("dialog_newPlant")
        dialog_newPlant.resize(330, 341)
        dialog_newPlant.setMaximumSize(QtCore.QSize(330, 341))
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_newPlant)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(dialog_newPlant)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(dialog_newPlant)
        self.label_9.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.addPlant_lineEdit_name = QtWidgets.QLineEdit(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPlant_lineEdit_name.setFont(font)
        self.addPlant_lineEdit_name.setMaxLength(30)
        self.addPlant_lineEdit_name.setObjectName("addPlant_lineEdit_name")
        self.horizontalLayout.addWidget(self.addPlant_lineEdit_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.addPlant_comboBox_source = QtWidgets.QComboBox(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPlant_comboBox_source.setFont(font)
        self.addPlant_comboBox_source.setObjectName("addPlant_comboBox_source")
        self.addPlant_comboBox_source.addItem("")
        self.addPlant_comboBox_source.addItem("")
        self.addPlant_comboBox_source.addItem("")
        self.addPlant_comboBox_source.addItem("")
        self.addPlant_comboBox_source.addItem("")
        self.gridLayout.addWidget(self.addPlant_comboBox_source, 0, 1, 1, 1)
        self.addPlant_lineEdit_capacity = QtWidgets.QLineEdit(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPlant_lineEdit_capacity.setFont(font)
        self.addPlant_lineEdit_capacity.setObjectName("addPlant_lineEdit_capacity")
        self.gridLayout.addWidget(self.addPlant_lineEdit_capacity, 1, 1, 1, 1)
        self.addPlant_lineEdit_efficiency = QtWidgets.QLineEdit(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPlant_lineEdit_efficiency.setFont(font)
        self.addPlant_lineEdit_efficiency.setObjectName("addPlant_lineEdit_efficiency")
        self.gridLayout.addWidget(self.addPlant_lineEdit_efficiency, 2, 1, 1, 1)
        self.addPlant_lineEdit_investmentCost = QtWidgets.QLineEdit(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPlant_lineEdit_investmentCost.setFont(font)
        self.addPlant_lineEdit_investmentCost.setObjectName("addPlant_lineEdit_investmentCost")
        self.gridLayout.addWidget(self.addPlant_lineEdit_investmentCost, 3, 1, 1, 1)
        self.addPlant_lineEdit_annualCost = QtWidgets.QLineEdit(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPlant_lineEdit_annualCost.setFont(font)
        self.addPlant_lineEdit_annualCost.setObjectName("addPlant_lineEdit_annualCost")
        self.gridLayout.addWidget(self.addPlant_lineEdit_annualCost, 4, 1, 1, 1)
        self.addPlant_lineEdit_variableCost = QtWidgets.QLineEdit(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPlant_lineEdit_variableCost.setFont(font)
        self.addPlant_lineEdit_variableCost.setObjectName("addPlant_lineEdit_variableCost")
        self.gridLayout.addWidget(self.addPlant_lineEdit_variableCost, 5, 1, 1, 1)
        self.addPlant_lineEdit_emissions = QtWidgets.QLineEdit(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPlant_lineEdit_emissions.setFont(font)
        self.addPlant_lineEdit_emissions.setObjectName("addPlant_lineEdit_emissions")
        self.gridLayout.addWidget(self.addPlant_lineEdit_emissions, 6, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.dialog_addPlant_buttonBox = QtWidgets.QDialogButtonBox(dialog_newPlant)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dialog_addPlant_buttonBox.setFont(font)
        self.dialog_addPlant_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialog_addPlant_buttonBox.setObjectName("dialog_addPlant_buttonBox")
        self.verticalLayout.addWidget(self.dialog_addPlant_buttonBox)

        self.retranslateUi(dialog_newPlant)
        QtCore.QMetaObject.connectSlotsByName(dialog_newPlant)
        dialog_newPlant.setTabOrder(self.addPlant_lineEdit_name, self.addPlant_comboBox_source)
        dialog_newPlant.setTabOrder(self.addPlant_comboBox_source, self.addPlant_lineEdit_capacity)
        dialog_newPlant.setTabOrder(self.addPlant_lineEdit_capacity, self.addPlant_lineEdit_efficiency)
        dialog_newPlant.setTabOrder(self.addPlant_lineEdit_efficiency, self.addPlant_lineEdit_investmentCost)
        dialog_newPlant.setTabOrder(self.addPlant_lineEdit_investmentCost, self.addPlant_lineEdit_annualCost)
        dialog_newPlant.setTabOrder(self.addPlant_lineEdit_annualCost, self.addPlant_lineEdit_variableCost)
        dialog_newPlant.setTabOrder(self.addPlant_lineEdit_variableCost, self.addPlant_lineEdit_emissions)

    def retranslateUi(self, dialog_newPlant):
        _translate = QtCore.QCoreApplication.translate
        dialog_newPlant.setWindowTitle(_translate("dialog_newPlant", "New plant"))
        self.label.setText(_translate("dialog_newPlant", "Add a new plant?"))
        self.label_9.setText(_translate("dialog_newPlant", "Name"))
        self.label_7.setText(_translate("dialog_newPlant", "Variable cost"))
        self.label_15.setText(_translate("dialog_newPlant", "MNOK"))
        self.label_4.setText(_translate("dialog_newPlant", "Efficiency"))
        self.label_2.setText(_translate("dialog_newPlant", "Source"))
        self.label_12.setText(_translate("dialog_newPlant", "%"))
        self.label_8.setText(_translate("dialog_newPlant", "Emissions"))
        self.label_3.setText(_translate("dialog_newPlant", "Capacity"))
        self.label_5.setText(_translate("dialog_newPlant", "Annual cost"))
        self.label_14.setText(_translate("dialog_newPlant", "MNOK/year"))
        self.label_16.setText(_translate("dialog_newPlant", "NOK/MWh"))
        self.label_17.setText(_translate("dialog_newPlant", "<html><head/><body><p>kg CO<span style=\" vertical-align:sub;\">2</span>eq/MWh</p></body></html>"))
        self.label_6.setText(_translate("dialog_newPlant", "investment cost"))
        self.label_11.setText(_translate("dialog_newPlant", "MW"))
        self.addPlant_comboBox_source.setItemText(0, _translate("dialog_newPlant", "Coal"))
        self.addPlant_comboBox_source.setItemText(1, _translate("dialog_newPlant", "Gas"))
        self.addPlant_comboBox_source.setItemText(2, _translate("dialog_newPlant", "PV"))
        self.addPlant_comboBox_source.setItemText(3, _translate("dialog_newPlant", "Wind"))
        self.addPlant_comboBox_source.setItemText(4, _translate("dialog_newPlant", "Nuclear"))

