# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plants_grid_test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_Player(object):
    def setupUi(self, MainWindow_Player):
        MainWindow_Player.setObjectName("MainWindow_Player")
        MainWindow_Player.resize(1173, 841)
        MainWindow_Player.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow_Player)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loadingscreen = QtWidgets.QWidget()
        self.loadingscreen.setObjectName("loadingscreen")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.loadingscreen)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.loadingscreen_title = QtWidgets.QLabel(self.loadingscreen)
        font = QtGui.QFont()
        font.setPointSize(96)
        self.loadingscreen_title.setFont(font)
        self.loadingscreen_title.setText("")
        self.loadingscreen_title.setPixmap(QtGui.QPixmap("../Resources/logo_test_huge.png"))
        self.loadingscreen_title.setObjectName("loadingscreen_title")
        self.verticalLayout_5.addWidget(self.loadingscreen_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.loadingscreen_begin = QtWidgets.QPushButton(self.loadingscreen)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.loadingscreen_begin.setFont(font)
        self.loadingscreen_begin.setAutoDefault(True)
        self.loadingscreen_begin.setFlat(True)
        self.loadingscreen_begin.setObjectName("loadingscreen_begin")
        self.verticalLayout_5.addWidget(self.loadingscreen_begin, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.stackedWidget.addWidget(self.loadingscreen)
        self.create = QtWidgets.QWidget()
        self.create.setObjectName("create")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.create)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.create_logo = QtWidgets.QLabel(self.create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_logo.sizePolicy().hasHeightForWidth())
        self.create_logo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.create_logo.setFont(font)
        self.create_logo.setText("")
        self.create_logo.setTextFormat(QtCore.Qt.PlainText)
        self.create_logo.setPixmap(QtGui.QPixmap("../Images/logo_test_medium.png"))
        self.create_logo.setScaledContents(True)
        self.create_logo.setObjectName("create_logo")
        self.verticalLayout_6.addWidget(self.create_logo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line = QtWidgets.QFrame(self.create)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line, 0, QtCore.Qt.AlignTop)
        self.create_introduction = QtWidgets.QLabel(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_introduction.setFont(font)
        self.create_introduction.setWordWrap(True)
        self.create_introduction.setObjectName("create_introduction")
        self.verticalLayout_6.addWidget(self.create_introduction, 0, QtCore.Qt.AlignTop)
        self.line_2 = QtWidgets.QFrame(self.create)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.create_firmNameLabel = QtWidgets.QLabel(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_firmNameLabel.setFont(font)
        self.create_firmNameLabel.setObjectName("create_firmNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.create_firmNameLabel)
        self.create_firmNameLineEdit = QtWidgets.QLineEdit(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_firmNameLineEdit.setFont(font)
        self.create_firmNameLineEdit.setObjectName("create_firmNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.create_firmNameLineEdit)
        self.create_firmMottoLabel = QtWidgets.QLabel(self.create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_firmMottoLabel.sizePolicy().hasHeightForWidth())
        self.create_firmMottoLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_firmMottoLabel.setFont(font)
        self.create_firmMottoLabel.setObjectName("create_firmMottoLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.create_firmMottoLabel)
        self.create_firmMottoLineEdit = QtWidgets.QLineEdit(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_firmMottoLineEdit.setFont(font)
        self.create_firmMottoLineEdit.setObjectName("create_firmMottoLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.create_firmMottoLineEdit)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.line_3 = QtWidgets.QFrame(self.create)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.create_next = QtWidgets.QPushButton(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_next.setFont(font)
        self.create_next.setObjectName("create_next")
        self.horizontalLayout_2.addWidget(self.create_next)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.create)
        self.connect = QtWidgets.QWidget()
        self.connect.setObjectName("connect")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.connect)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.connect_logo = QtWidgets.QLabel(self.connect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_logo.sizePolicy().hasHeightForWidth())
        self.connect_logo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.connect_logo.setFont(font)
        self.connect_logo.setText("")
        self.connect_logo.setPixmap(QtGui.QPixmap("../Images/logo_test_medium.png"))
        self.connect_logo.setObjectName("connect_logo")
        self.verticalLayout_7.addWidget(self.connect_logo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_4 = QtWidgets.QFrame(self.connect)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_7.addWidget(self.line_4)
        self.label = QtWidgets.QLabel(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.line_5 = QtWidgets.QFrame(self.connect)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_7.addWidget(self.line_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.ipAddressLabel = QtWidgets.QLabel(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ipAddressLabel.setFont(font)
        self.ipAddressLabel.setObjectName("ipAddressLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ipAddressLabel)
        self.ipAddressLineEdit = QtWidgets.QLineEdit(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ipAddressLineEdit.setFont(font)
        self.ipAddressLineEdit.setObjectName("ipAddressLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ipAddressLineEdit)
        self.portLabel = QtWidgets.QLabel(self.connect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLabel.sizePolicy().hasHeightForWidth())
        self.portLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.portLineEdit = QtWidgets.QLineEdit(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portLineEdit.setFont(font)
        self.portLineEdit.setObjectName("portLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.portLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout_7.addLayout(self.formLayout_2)
        self.line_6 = QtWidgets.QFrame(self.connect)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_7.addWidget(self.line_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.connect_next = QtWidgets.QPushButton(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.connect_next.setFont(font)
        self.connect_next.setObjectName("connect_next")
        self.horizontalLayout.addWidget(self.connect_next)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.connect)
        self.lobby = QtWidgets.QWidget()
        self.lobby.setObjectName("lobby")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.lobby)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_7 = QtWidgets.QFrame(self.lobby)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_8.addWidget(self.line_7)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lobby_name_player2 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_name_player2.sizePolicy().hasHeightForWidth())
        self.lobby_name_player2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_name_player2.setFont(font)
        self.lobby_name_player2.setObjectName("lobby_name_player2")
        self.gridLayout.addWidget(self.lobby_name_player2, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lobby_label_ready1 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_label_ready1.sizePolicy().hasHeightForWidth())
        self.lobby_label_ready1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_label_ready1.setFont(font)
        self.lobby_label_ready1.setObjectName("lobby_label_ready1")
        self.gridLayout.addWidget(self.lobby_label_ready1, 1, 1, 1, 1)
        self.lobby_label_ready2 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_label_ready2.sizePolicy().hasHeightForWidth())
        self.lobby_label_ready2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_label_ready2.setFont(font)
        self.lobby_label_ready2.setObjectName("lobby_label_ready2")
        self.gridLayout.addWidget(self.lobby_label_ready2, 2, 1, 1, 1)
        self.lobby_name_player1 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_name_player1.sizePolicy().hasHeightForWidth())
        self.lobby_name_player1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_name_player1.setFont(font)
        self.lobby_name_player1.setObjectName("lobby_name_player1")
        self.gridLayout.addWidget(self.lobby_name_player1, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lobby_name_player4 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_name_player4.sizePolicy().hasHeightForWidth())
        self.lobby_name_player4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_name_player4.setFont(font)
        self.lobby_name_player4.setObjectName("lobby_name_player4")
        self.gridLayout.addWidget(self.lobby_name_player4, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lobby_name_player3 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_name_player3.sizePolicy().hasHeightForWidth())
        self.lobby_name_player3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_name_player3.setFont(font)
        self.lobby_name_player3.setObjectName("lobby_name_player3")
        self.gridLayout.addWidget(self.lobby_name_player3, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lobby_label_ready3 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_label_ready3.sizePolicy().hasHeightForWidth())
        self.lobby_label_ready3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_label_ready3.setFont(font)
        self.lobby_label_ready3.setObjectName("lobby_label_ready3")
        self.gridLayout.addWidget(self.lobby_label_ready3, 3, 1, 1, 1)
        self.lobby_label_ready6 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_label_ready6.sizePolicy().hasHeightForWidth())
        self.lobby_label_ready6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_label_ready6.setFont(font)
        self.lobby_label_ready6.setObjectName("lobby_label_ready6")
        self.gridLayout.addWidget(self.lobby_label_ready6, 6, 1, 1, 1)
        self.lobby_name_player5 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_name_player5.sizePolicy().hasHeightForWidth())
        self.lobby_name_player5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_name_player5.setFont(font)
        self.lobby_name_player5.setObjectName("lobby_name_player5")
        self.gridLayout.addWidget(self.lobby_name_player5, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lobby_name_player6 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_name_player6.sizePolicy().hasHeightForWidth())
        self.lobby_name_player6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_name_player6.setFont(font)
        self.lobby_name_player6.setObjectName("lobby_name_player6")
        self.gridLayout.addWidget(self.lobby_name_player6, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lobby_label_ready5 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_label_ready5.sizePolicy().hasHeightForWidth())
        self.lobby_label_ready5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_label_ready5.setFont(font)
        self.lobby_label_ready5.setObjectName("lobby_label_ready5")
        self.gridLayout.addWidget(self.lobby_label_ready5, 5, 1, 1, 1)
        self.lobby_label_ready4 = QtWidgets.QLabel(self.lobby)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lobby_label_ready4.sizePolicy().hasHeightForWidth())
        self.lobby_label_ready4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_label_ready4.setFont(font)
        self.lobby_label_ready4.setObjectName("lobby_label_ready4")
        self.gridLayout.addWidget(self.lobby_label_ready4, 4, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.line_8 = QtWidgets.QFrame(self.lobby)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_8.addWidget(self.line_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.lobby_button = QtWidgets.QPushButton(self.lobby)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lobby_button.setFont(font)
        self.lobby_button.setObjectName("lobby_button")
        self.horizontalLayout_3.addWidget(self.lobby_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.lobby)
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_22 = QtWidgets.QLabel(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15 = QtWidgets.QLabel(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_23 = QtWidgets.QLabel(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.line_9 = QtWidgets.QFrame(self.main)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_9.addWidget(self.line_9, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.main_button_main = QtWidgets.QPushButton(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_main.sizePolicy().hasHeightForWidth())
        self.main_button_main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.main_button_main.setFont(font)
        self.main_button_main.setCheckable(True)
        self.main_button_main.setChecked(True)
        self.main_button_main.setFlat(True)
        self.main_button_main.setObjectName("main_button_main")
        self.verticalLayout_10.addWidget(self.main_button_main, 0, QtCore.Qt.AlignLeft)
        self.main_button_plants = QtWidgets.QPushButton(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_plants.sizePolicy().hasHeightForWidth())
        self.main_button_plants.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.main_button_plants.setFont(font)
        self.main_button_plants.setCheckable(False)
        self.main_button_plants.setChecked(False)
        self.main_button_plants.setFlat(True)
        self.main_button_plants.setObjectName("main_button_plants")
        self.verticalLayout_10.addWidget(self.main_button_plants, 0, QtCore.Qt.AlignLeft)
        self.main_button_invest = QtWidgets.QPushButton(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_invest.sizePolicy().hasHeightForWidth())
        self.main_button_invest.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.main_button_invest.setFont(font)
        self.main_button_invest.setCheckable(False)
        self.main_button_invest.setChecked(False)
        self.main_button_invest.setFlat(True)
        self.main_button_invest.setObjectName("main_button_invest")
        self.verticalLayout_10.addWidget(self.main_button_invest, 0, QtCore.Qt.AlignLeft)
        self.main_button_market = QtWidgets.QPushButton(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_market.sizePolicy().hasHeightForWidth())
        self.main_button_market.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.main_button_market.setFont(font)
        self.main_button_market.setCheckable(False)
        self.main_button_market.setChecked(False)
        self.main_button_market.setFlat(True)
        self.main_button_market.setObjectName("main_button_market")
        self.verticalLayout_10.addWidget(self.main_button_market, 0, QtCore.Qt.AlignLeft)
        self.main_button_info = QtWidgets.QPushButton(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_info.sizePolicy().hasHeightForWidth())
        self.main_button_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.main_button_info.setFont(font)
        self.main_button_info.setCheckable(False)
        self.main_button_info.setChecked(False)
        self.main_button_info.setFlat(True)
        self.main_button_info.setObjectName("main_button_info")
        self.verticalLayout_10.addWidget(self.main_button_info, 0, QtCore.Qt.AlignLeft)
        self.label_20 = QtWidgets.QLabel(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_10.addWidget(self.label_20)
        self.main_button_quit = QtWidgets.QPushButton(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_button_quit.sizePolicy().hasHeightForWidth())
        self.main_button_quit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.main_button_quit.setFont(font)
        self.main_button_quit.setCheckable(False)
        self.main_button_quit.setChecked(False)
        self.main_button_quit.setFlat(True)
        self.main_button_quit.setObjectName("main_button_quit")
        self.verticalLayout_10.addWidget(self.main_button_quit, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.line_11 = QtWidgets.QFrame(self.main)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_4.addWidget(self.line_11)
        self.label_16 = QtWidgets.QLabel(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_16.setFont(font)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.main)
        self.page_plants = QtWidgets.QWidget()
        self.page_plants.setObjectName("page_plants")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_plants)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.page_plants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4 = QtWidgets.QLabel(self.page_plants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2 = QtWidgets.QLabel(self.page_plants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.line_10 = QtWidgets.QFrame(self.page_plants)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_11.addWidget(self.line_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton = QtWidgets.QPushButton(self.page_plants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_12.addWidget(self.pushButton)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_plants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_12.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.page_plants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_12.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.page_plants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_12.addWidget(self.pushButton_10)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem6)
        self.pushButton_11 = QtWidgets.QPushButton(self.page_plants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(150, 100))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_12.addWidget(self.pushButton_11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.line_12 = QtWidgets.QFrame(self.page_plants)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_7.addWidget(self.line_12)
        self.plants_gridLayout = QtWidgets.QGridLayout()
        self.plants_gridLayout.setObjectName("plants_gridLayout")
        self.label_7 = QtWidgets.QLabel(self.page_plants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.plants_gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_plants)
        self.label_6.setObjectName("label_6")
        self.plants_gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_plants)
        self.label_8.setObjectName("label_8")
        self.plants_gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.plants_gridLayout)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.stackedWidget.addWidget(self.page_plants)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow_Player.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_Player)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1173, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_Player.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_Player)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Player.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_Player)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Player)

    def retranslateUi(self, MainWindow_Player):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Player.setWindowTitle(_translate("MainWindow_Player", "MainWindow"))
        self.loadingscreen_begin.setText(_translate("MainWindow_Player", "Click to begin"))
        self.create_introduction.setText(_translate("MainWindow_Player", "Welcome to PowerTrade.\n"
"In This game players will compete against eachother on the power market. You will invest in power production and use skills, knowledge and cunning to create the highest profit.\n"
"Before starting to compete in the market you need to create a company. Please input the company name and motto and press next to continue."))
        self.create_firmNameLabel.setText(_translate("MainWindow_Player", "Firm name"))
        self.create_firmMottoLabel.setText(_translate("MainWindow_Player", "Firm motto"))
        self.create_next.setText(_translate("MainWindow_Player", "Next"))
        self.label.setText(_translate("MainWindow_Player", "Please input the IP-address and port number provided by the host of the game. "))
        self.ipAddressLabel.setText(_translate("MainWindow_Player", "IP-address"))
        self.portLabel.setText(_translate("MainWindow_Player", "Port"))
        self.connect_next.setText(_translate("MainWindow_Player", "Next"))
        self.label_3.setText(_translate("MainWindow_Player", "PowerTrade"))
        self.lobby_name_player2.setText(_translate("MainWindow_Player", "Player 2"))
        self.lobby_label_ready1.setText(_translate("MainWindow_Player", "Not ready"))
        self.lobby_label_ready2.setText(_translate("MainWindow_Player", "Not ready"))
        self.lobby_name_player1.setText(_translate("MainWindow_Player", "Player 1"))
        self.lobby_name_player4.setText(_translate("MainWindow_Player", "Player 4"))
        self.lobby_name_player3.setText(_translate("MainWindow_Player", "Player 3"))
        self.lobby_label_ready3.setText(_translate("MainWindow_Player", "Not ready"))
        self.lobby_label_ready6.setText(_translate("MainWindow_Player", "Not ready"))
        self.lobby_name_player5.setText(_translate("MainWindow_Player", "Player 5"))
        self.lobby_name_player6.setText(_translate("MainWindow_Player", "Player 6"))
        self.lobby_label_ready5.setText(_translate("MainWindow_Player", "Not ready"))
        self.lobby_label_ready4.setText(_translate("MainWindow_Player", "Not ready"))
        self.lobby_button.setText(_translate("MainWindow_Player", "Ready"))
        self.label_22.setText(_translate("MainWindow_Player", "Phase"))
        self.label_15.setText(_translate("MainWindow_Player", "Company name"))
        self.label_23.setText(_translate("MainWindow_Player", "Money"))
        self.main_button_main.setText(_translate("MainWindow_Player", "Main"))
        self.main_button_plants.setText(_translate("MainWindow_Player", "Plants"))
        self.main_button_invest.setText(_translate("MainWindow_Player", "Invest"))
        self.main_button_market.setText(_translate("MainWindow_Player", "Market"))
        self.main_button_info.setText(_translate("MainWindow_Player", "Info"))
        self.main_button_quit.setText(_translate("MainWindow_Player", "Quit"))
        self.label_16.setText(_translate("MainWindow_Player", "THE MAIN SCREEN! IT IS HUGE WITH A LOT OF SPACE FOR STUFF"))
        self.label_5.setText(_translate("MainWindow_Player", "Phase"))
        self.label_4.setText(_translate("MainWindow_Player", "Company name"))
        self.label_2.setText(_translate("MainWindow_Player", "Money"))
        self.pushButton.setText(_translate("MainWindow_Player", "Main"))
        self.pushButton_8.setText(_translate("MainWindow_Player", "Plants"))
        self.pushButton_9.setText(_translate("MainWindow_Player", "Invest"))
        self.pushButton_10.setText(_translate("MainWindow_Player", "Market"))
        self.pushButton_11.setText(_translate("MainWindow_Player", "Quit"))
        self.label_7.setText(_translate("MainWindow_Player", "Plants"))
        self.label_6.setText(_translate("MainWindow_Player", "TextLabel"))
        self.label_8.setText(_translate("MainWindow_Player", "TEST"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_Player = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Player()
    ui.setupUi(MainWindow_Player)
    MainWindow_Player.show()
    sys.exit(app.exec_())

