# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stackedWidget_test.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loadingscreen = QtWidgets.QWidget()
        self.loadingscreen.setObjectName("loadingscreen")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.loadingscreen)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.loadingscreen_title = QtWidgets.QLabel(self.loadingscreen)
        font = QtGui.QFont()
        font.setPointSize(96)
        self.loadingscreen_title.setFont(font)
        self.loadingscreen_title.setObjectName("loadingscreen_title")
        self.verticalLayout_5.addWidget(self.loadingscreen_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.loadingscreen_begin = QtWidgets.QPushButton(self.loadingscreen)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.loadingscreen_begin.setFont(font)
        self.loadingscreen_begin.setFlat(True)
        self.loadingscreen_begin.setObjectName("loadingscreen_begin")
        self.verticalLayout_5.addWidget(self.loadingscreen_begin, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.stackedWidget.addWidget(self.loadingscreen)
        self.create = QtWidgets.QWidget()
        self.create.setObjectName("create")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.create)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.create_title = QtWidgets.QLabel(self.create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_title.sizePolicy().hasHeightForWidth())
        self.create_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.create_title.setFont(font)
        self.create_title.setObjectName("create_title")
        self.verticalLayout_6.addWidget(self.create_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line = QtWidgets.QFrame(self.create)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line, 0, QtCore.Qt.AlignTop)
        self.create_introduction = QtWidgets.QLabel(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_introduction.setFont(font)
        self.create_introduction.setWordWrap(True)
        self.create_introduction.setObjectName("create_introduction")
        self.verticalLayout_6.addWidget(self.create_introduction, 0, QtCore.Qt.AlignTop)
        self.line_2 = QtWidgets.QFrame(self.create)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.create_firmNameLabel = QtWidgets.QLabel(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_firmNameLabel.setFont(font)
        self.create_firmNameLabel.setObjectName("create_firmNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.create_firmNameLabel)
        self.create_firmNameLineEdit = QtWidgets.QLineEdit(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_firmNameLineEdit.setFont(font)
        self.create_firmNameLineEdit.setObjectName("create_firmNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.create_firmNameLineEdit)
        self.create_firmMottoLabel = QtWidgets.QLabel(self.create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_firmMottoLabel.sizePolicy().hasHeightForWidth())
        self.create_firmMottoLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_firmMottoLabel.setFont(font)
        self.create_firmMottoLabel.setObjectName("create_firmMottoLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.create_firmMottoLabel)
        self.create_firmMottoLineEdit = QtWidgets.QLineEdit(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_firmMottoLineEdit.setFont(font)
        self.create_firmMottoLineEdit.setObjectName("create_firmMottoLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.create_firmMottoLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.line_3 = QtWidgets.QFrame(self.create)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.create_next = QtWidgets.QPushButton(self.create)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.create_next.setFont(font)
        self.create_next.setObjectName("create_next")
        self.horizontalLayout_2.addWidget(self.create_next)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.create)
        self.connect = QtWidgets.QWidget()
        self.connect.setObjectName("connect")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.connect)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.connect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.line_4 = QtWidgets.QFrame(self.connect)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_7.addWidget(self.line_4)
        self.label = QtWidgets.QLabel(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.line_5 = QtWidgets.QFrame(self.connect)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_7.addWidget(self.line_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.iPAddressLabel = QtWidgets.QLabel(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.iPAddressLabel.setFont(font)
        self.iPAddressLabel.setObjectName("iPAddressLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iPAddressLabel)
        self.iPAddressLineEdit = QtWidgets.QLineEdit(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.iPAddressLineEdit.setFont(font)
        self.iPAddressLineEdit.setObjectName("iPAddressLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.iPAddressLineEdit)
        self.portLabel = QtWidgets.QLabel(self.connect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLabel.sizePolicy().hasHeightForWidth())
        self.portLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.portLineEdit = QtWidgets.QLineEdit(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.portLineEdit.setFont(font)
        self.portLineEdit.setObjectName("portLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.portLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout_7.addLayout(self.formLayout_2)
        self.line_6 = QtWidgets.QFrame(self.connect)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_7.addWidget(self.line_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(self.connect)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.connect)
        self.lobby = QtWidgets.QWidget()
        self.lobby.setObjectName("lobby")
        self.stackedWidget.addWidget(self.lobby)
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.stackedWidget.addWidget(self.main)
        self.plants = QtWidgets.QWidget()
        self.plants.setObjectName("plants")
        self.stackedWidget.addWidget(self.plants)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadingscreen_title.setText(_translate("MainWindow", "PowerTrade"))
        self.loadingscreen_begin.setText(_translate("MainWindow", "Click to begin"))
        self.create_title.setText(_translate("MainWindow", "PowerTrade"))
        self.create_introduction.setText(_translate("MainWindow", "Welcome to PowerTrade. Before starting to compete in the market you need to create a company. Please input the company name and motto and press next to continue."))
        self.create_firmNameLabel.setText(_translate("MainWindow", "Firm name"))
        self.create_firmMottoLabel.setText(_translate("MainWindow", "Firm motto"))
        self.create_next.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "PowerTrade"))
        self.label.setText(_translate("MainWindow", "Please input the IP-address and port number provided by the host of the game. "))
        self.iPAddressLabel.setText(_translate("MainWindow", "IP-address"))
        self.portLabel.setText(_translate("MainWindow", "Port"))
        self.pushButton.setText(_translate("MainWindow", "Next"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
